-- 0134_provider_trust_fields.sql
-- Tanda 1 de mejoras de UX de perfil (inspiradas en el directorio de Iluminemos):
--   - profiles.year_started   : año en que el prestador inició actividad (señal de
--                               antigüedad sin exponer edad). NULL = no declarado.
--   - profiles.certified_staff: personal certificado (Sí/No). NULL = no declarado.
-- Ambos OPCIONALES (no se piden en el alta; se editan luego desde el panel) para no
-- subir la tasa de registros incompletos.
--
-- Como directorio_publico es un UNION posicional (ver aviso en 0094), recrear la
-- vista añadiendo las 2 columnas EN AMBAS RAMAS, en la misma posición (tras
-- neuro_conditions). Se preserva el predicado de gracia de 0132 y la columna
-- provider_types. Idempotente.

alter table public.profiles add column if not exists year_started    integer;
alter table public.profiles add column if not exists certified_staff boolean;

-- Recreación de la vista (superconjunto de profiles + fichas). Column-count de
-- ambas ramas debe coincidir; las 2 nuevas van tras neuro_conditions en las dos.
drop view if exists public.directorio_publico;

create view public.directorio_publico
with (security_invoker = on) as
 SELECT p.id,
    p.role,
    p.full_name,
    p.avatar_url,
    p.phone,
    p.bio,
    p.qr_token,
    p.provider_type,
    p.business_name,
    p.website_url,
    p.address,
    p.city,
    p.country,
    p.is_verified,
    p.is_published,
    p.latitude,
    p.longitude,
    p.created_at,
    p.updated_at,
    p.birth_date,
    p.gender,
    p.condition,
    p.state,
    p.municipality,
    p.is_company,
    p.services_offered,
    p.membership_status,
    p.membership_due_at,
    p.membership_paid_until,
    p.stripe_customer_id,
    p.stripe_subscription_id,
    p.promo_code_used,
    p.dial_code,
    p.website,
    p.instagram,
    p.tiktok,
    p.facebook,
    p.cedula_profesional,
    p.rules_version_accepted,
    p.rules_accepted_at,
    p.stripe_connect_id,
    p.stripe_charges_enabled,
    p.accepts_payments,
    p.consultation_amount,
    p.consultation_currency,
    p.rfc,
    p.public_key,
    p.fiscal_razon_social,
    p.fiscal_regimen,
    p.fiscal_uso_cfdi,
    p.fiscal_cp,
    p.fiscal_direccion,
    p.fiscal_email,
    p.fiscal_tax_id,
    p.fiscal_country,
    p.school_grades,
    p.account_type,
    p.life_stage,
    p.interests,
    p.comms_opt_in,
    p.title_prefix,
    p.profession,
    p.whatsapp,
    p.booking_url,
    p.linkedin,
    p.specialties,
    p.modalities,
    p.age_ranges,
    p.intervention_areas,
    p.provider_details,
    p.product_categories,
    p.products_offered,
    p.sales_channels,
    p.shipping_coverage,
    p.price_range,
    p.search_tsv,
    p.badge_level,
    p.member_no,
    p.wants_founder,
    p.referred_by,
    p.referred_at,
    p.referral_credit_pct,
    p.is_medical_override,
    p.suspended_at,
    p.suspend_until,
    p.pre_suspend_published,
    p.winback_until,
    p.neuroaffirming,
    p.accepts_neuromundi_id,
    p.is_advisor,
    p.sections,
    p.neuro_conditions,
    p.year_started,
    p.certified_staff,
    'perfil'::text AS origen,
    NULL::text AS clee,
    false AS reclamable,
    ARRAY[p.provider_type] AS provider_types
   FROM profiles p
  WHERE p.role = 'provider'::text AND p.rules_version_accepted IS NOT NULL AND (p.is_published AND (p.membership_status = ANY (ARRAY['active'::text, 'exempt'::text, 'past_due'::text])) OR p.membership_status = 'pending'::text AND now() < COALESCE(( SELECT fm.grace_until
           FROM founder_members fm
          WHERE fm.user_id = p.id), p.created_at + '30 days'::interval))
UNION ALL
 SELECT d.id,
    'provider'::text AS role,
    d.nombre AS full_name,
    NULL::text AS avatar_url,
    d.telefono AS phone,
    NULL::text AS bio,
    d.id AS qr_token,
    d.provider_type,
    d.nombre AS business_name,
    d.sitio_web AS website_url,
    d.direccion AS address,
    d.ciudad AS city,
    'México'::text AS country,
    false AS is_verified,
    true AS is_published,
    d.lat AS latitude,
    d.lng AS longitude,
    d.creada_en AS created_at,
    d.actualizada_en AS updated_at,
    NULL::date AS birth_date,
    NULL::text AS gender,
    NULL::text AS condition,
    d.estado AS state,
    d.ciudad AS municipality,
    false AS is_company,
    d.especializacion AS services_offered,
    'exempt'::text AS membership_status,
    NULL::timestamp with time zone AS membership_due_at,
    NULL::timestamp with time zone AS membership_paid_until,
    NULL::text AS stripe_customer_id,
    NULL::text AS stripe_subscription_id,
    NULL::text AS promo_code_used,
    NULL::text AS dial_code,
    d.sitio_web AS website,
    NULL::text AS instagram,
    NULL::text AS tiktok,
    NULL::text AS facebook,
    NULL::text AS cedula_profesional,
    NULL::text AS rules_version_accepted,
    NULL::timestamp with time zone AS rules_accepted_at,
    NULL::text AS stripe_connect_id,
    false AS stripe_charges_enabled,
    false AS accepts_payments,
    NULL::numeric AS consultation_amount,
    NULL::text AS consultation_currency,
    NULL::text AS rfc,
    NULL::text AS public_key,
    NULL::text AS fiscal_razon_social,
    NULL::text AS fiscal_regimen,
    NULL::text AS fiscal_uso_cfdi,
    NULL::text AS fiscal_cp,
    NULL::text AS fiscal_direccion,
    NULL::text AS fiscal_email,
    NULL::text AS fiscal_tax_id,
    NULL::text AS fiscal_country,
    '{}'::text[] AS school_grades,
    NULL::text AS account_type,
    NULL::text AS life_stage,
    '{}'::text[] AS interests,
    false AS comms_opt_in,
    NULL::text AS title_prefix,
    NULL::text AS profession,
    NULL::text AS whatsapp,
    NULL::text AS booking_url,
    NULL::text AS linkedin,
    '{}'::text[] AS specialties,
    '{}'::text[] AS modalities,
    '{}'::text[] AS age_ranges,
    '{}'::text[] AS intervention_areas,
    '{}'::jsonb AS provider_details,
    '{}'::text[] AS product_categories,
    '{}'::text[] AS products_offered,
    '{}'::text[] AS sales_channels,
    '{}'::text[] AS shipping_coverage,
    NULL::text AS price_range,
    NULL::tsvector AS search_tsv,
    NULL::text AS badge_level,
    NULL::bigint AS member_no,
    false AS wants_founder,
    NULL::bigint AS referred_by,
    NULL::timestamp with time zone AS referred_at,
    0::numeric AS referral_credit_pct,
    NULL::boolean AS is_medical_override,
    NULL::timestamp with time zone AS suspended_at,
    NULL::timestamp with time zone AS suspend_until,
    NULL::boolean AS pre_suspend_published,
    NULL::timestamp with time zone AS winback_until,
    false AS neuroaffirming,
    false AS accepts_neuromundi_id,
    false AS is_advisor,
    COALESCE(d.sections, '{}'::text[]) AS sections,
    '{}'::text[] AS neuro_conditions,
    NULL::integer AS year_started,
    NULL::boolean AS certified_staff,
    'ficha'::text AS origen,
    d.clee,
    true AS reclamable,
    d.provider_types
   FROM directorio d
  WHERE d.estado_revision = 'publicado'::text AND NOT d.baja_solicitada AND d.reclamada_por IS NULL AND NOT (EXISTS ( SELECT 1
           FROM profiles p
          WHERE p.id = d.id AND p.is_published AND p.role = 'provider'::text));

grant select on public.directorio_publico to anon, authenticated;
